### ISSUE TITLE
x command missing

### ISSUE THREAD

**Issue by ninuzzo** [geany/geany-plugins#818] opened 2019-02-07 00:51 UTC
In the Vimode plugin, you should fully implement the basic x command. I miss it a lot. E.g. 5x deletes 5 chars to the right, included the character under the cursor. If there are less than 5 chars from the current current position to the end of line, only that much chars are deleted. It only works for 1 character. I don't know about the CVS version, I'm talking of the last 1.34 release.

**Comment by elextr** [comment] 2019-02-07 01:33
Geany and especially geany-plugins are volunteer projects, and in the case of plugins usually a single person.  Demanding "You should implement ..." is usually less effective than contributing a patch.

**Comment by techee** [comment] 2019-02-09 23:20
@ninuzzo Thanks for reporting. Would you try if #820 fixes the issue?

**Comment by go2null** [comment] 2019-05-02 17:26
Using vimode 1.34 on Geany 1.34.1.

Pressing any number switches to insert mode an inserts the number.
So, `5x` inserts `5x` rather than delete 5 characters.

**Comment by techee** [comment] 2019-05-03 12:33
@go2null Would you try 1.35? I believe the original problem was fixed in #820 but I can't reproduce the issue you reported.

**Comment by go2null** [comment] 2019-05-03 19:16
v1.35 is not available in my distro (Void Linux) yet; will confirm once in.

**Comment by techee** [comment] 2019-05-07 05:36
I'm closing this bug report for now as I think the original problem is fixed. If you run into some problem with 1.35, please create a new bug report.

**Closed by techee** 2019-05-07 05:36 UTC
Labels: enhancement, plugin/vimode
