### ISSUE TITLE
Plugin "tag pair highlighter plugin for Geany" issue => Alphabetic character "<" makes Geany close.

### ISSUE THREAD

**Issue by Nilsb13** [geany/geany-plugins#553] opened 2017-03-30 14:15 UTC
Hi !

Plugin "tag pair highlighter plugin for Geany" issue : Alphabetic character "<" makes Geany close.

Geany 1.27
Running on Ubuntu 16.04 LTS
This is a copy of original post : https://github.com/geany/geany/issues/1455

on the attached (sorry, I cannot attach PHP file) PHP file, at line 1583,
I have the following code (started before by /*, and finishing after by */) :
* V...|.......................Jour courant..................................>|<...................................Lendemain.................................................>|
When I write the "<" character, on this line 1583, Geany closes.

In /var/log/syslog there is :
Mar 30 12:58:29 PRINCIPAL kernel: [ 2151.269486] geany[12005]: segfault at 0 ip 00007f1b1a5cf9de sp 00007ffe7d451aa8 error 4 in libc-2.23.so[7f1b1a531000+1bf000]
Mar 30 13:05:45 PRINCIPAL kernel: [ 2586.680237] geany[13373]: segfault at 0 ip 00007fd0b0b929de sp 00007fffe225d0b8 error 4 in libc-2.23.so[7fd0b0af4000+1bf000]
Mar 30 13:08:16 PRINCIPAL kernel: [ 2737.718143] geany[13586]: segfault at 0 ip 00007fd4ff5ae9de sp 00007ffcc369f738 error 4 in libc-2.23.so[7fd4ff510000+1bf000]
and more ...

On this line 1583, " *	V...|.......................Jour courant.....".

I removed the first "<", before the words "Jour courant", just after the first "|" character, and I cannot write it back, because Geany closes each time I trie.

Original was : "V...|<.......................Jour courant....."."

If I clic before the second "<" (do not look for the first one, it does not exist anymore), before the word "Lendemain", nothing happen.

If I clic after the second "<" (do not look for the first one, it does not exist anymore), Geany closes.

If I clic after the last ">" Geany does not close.

Let me know if you want my PHP file.
Thank you for looking about it ...
Nils

.../...

I removed the "tag pair highlighter plugin for Geany" plugin,
the bug disappeared.

So, this plugin is bugged with "<" Character.

.../...

I re installed and enabled "tag pair highlighter plugin for Geany" plugin,
bug came back.

I disabled "tag pair highlighter plugin for Geany" plugin,
bug disappeared again.

Yes, the issue is coming from this plugin.

.../...

Good that you have debugged it to the plugin, now you should report it to the plugins issues list (sorry I don't think Github can transfer issues).
Plugins are maintained by individuals who may not watch the Geany issues.
Also please include version of Geany and platform you are running on.

**Comment by codebrainz** [comment] 2017-03-30 14:34
Possible duplicate of #442, #446, [#130](https://sourceforge.net/p/geany-plugins/bugs/130/), [#989](https://github.com/geany/geany/issues/989), and [#1016](https://github.com/geany/geany/issues/1016).

**Comment by LarsGit223** [comment] 2017-10-17 20:10
@Nilsb13: I cannot re-produce the problem with the current development version. But maybe I am doing something wrong. Could you please check if you still encounter the crash with the latest geany and geany plugins version?

**Comment by codebrainz** [comment] 2017-10-17 23:11
This was fixed in #447. Closing as duplicate. Feel free to re-open/make new issue if it still occurs with latest version of Geany. Thanks for reporting!

**Closed by codebrainz** 2017-10-17 23:11 UTC
