### ISSUE TITLE
[vimode] Cannot search or go to lines

### ISSUE THREAD

**Issue by Francexi** [geany/geany-plugins#961] opened 2020-03-15 12:01 UTC
If i press "/" and a string, or ":" and a line number, then Enter, the command is not issued and the textbox on the top satys on screen. Also no search is performed while writing.

I'm on Slackware-current, geany 1.35, geany-plugins git cloned

**Comment by techee** [comment] 2020-03-23 13:53
This sounds like a duplicate of #941 . I'm closing this bug report and let's continue the discussion there.

**Closed by techee** 2020-03-23 13:53 UTC
Labels: plugin/vimode
