### ISSUE TITLE
vimode: :[integer] doesn't jump to the line number

### ISSUE THREAD

**Issue by levu42** [geany/geany-plugins#937] opened 2019-12-24 20:59 UTC
In Vi(m), :[integer] brings the cursor to this line number. This doesn't work with the vimode plugin.

Version: 1.36-2 (arch linux)

**Comment by techee** [comment] 2020-03-23 14:02
Is it the same problem with the command window not disappearing like in #941 ? If so, we can close this bug report and continue the discussion there.

**Comment by techee** [comment] 2020-05-06 16:57
I guess this is a duplicate of #941, closing.

**Closed by techee** 2020-05-06 16:57 UTC
Labels: plugin/vimode
