### ISSUE TITLE
Wrap Lines In Overview Plugin

### ISSUE THREAD

**Issue by b4n** [geany/geany-plugins#506] opened 2016-11-23 10:07 UTC
_Moved from geany/geany#1319, originally opened by @483768903474589 on November 23, 2016._

Hi

The lines do not wrap in the Overview plugin when line wrapping is enabled in the editor. Would making the lines wrap in the Overview be possible to implement?

I have the latest version of Geany.

Thanks
Fred

**Comment by codebrainz** [comment] 2016-11-23 10:15
Duplicate of #321

**Closed by codebrainz** 2016-11-23 10:15 UTC
Labels: duplicate, enhancement, plugin/overview

**Comment by b4n** [comment] 2016-11-23 10:21
@codebrainz oops, sorry, I didn't check for dupes indeed.

**Comment by 483768903474589** [comment] 2016-11-23 10:35
Please implement this. Thanks.
