### ISSUE TITLE
Plugin is offering diff etc on files not placed inside a VCS working copy

### ISSUE THREAD

**Issue by frlan** [geany/geany-plugins#503] opened 2016-11-12 18:13 UTC
1. Create a file in /tmp
2. Try to do a diff/* for that file

**Comment by nomadbyte** [comment] 2020-11-13 21:06
Cannot reproduce since [v1.36](../releases/tag/1.36.0).

Likely related to #741 and #970. Fixed in #967 .

**Comment by eht16** [comment] 2022-02-20 16:21
Cannot reproduce too, closing and assuming it was fixed by the mentioned change.

**Closed by eht16** 2022-02-20 16:21 UTC
Labels: plugin/geanyvc
