### ISSUE TITLE
Projectorganizer external dirs and tagging is not compatible

### ISSUE THREAD

**Issue by derba** [geany/geany-plugins#330] opened 2016-01-13 15:33 UTC
When I add external directories, those are not tagged by Geany's tagger and GeanyCtags plugin. Project base path is considered only.

**Comment by techee** [comment] 2016-01-13 21:52
@derba This should work (I'm using it myself very often). What filetypes do you have in your project and in the external directory?

**Comment by techee** [comment] 2016-01-13 22:11
Just check if the file extensions you use are assigned to the right filetype under

Tools->Configuration files->filetype_extensions.conf

Also make sure the given filetype is actually parsed by Geany (not all filetypes are supported) - when the file is open, go to the Symbols tab and check if something appears there.

**Comment by derba** [comment] 2016-01-14 12:53
I have a C file in the project directory and several C modules in the directories I added as external directories. When I use GeanyCtags plugin, "Project/Generate tags" menu item appears. When I click that, files in external dirs are not tagged.

At Messages the following appears:

    find . -not -path '*/\.*' | ctags --totals --fields=fKsSt --extra=-fq --c-kinds=+p --sort=foldcase --excmd=number -L - -f /home/username/projects/Proj.tags (in directory: /home/username/projects/Proj/)

I think find should be invoked for each directory. The command should look like this (at least on Linux/Unix):

    cat <(find ...) <(find extdir1 ...) <(find extdir2 ...) | ctags ...

**Comment by techee** [comment] 2016-01-14 16:20
@derba You are mixing the functionality of two different plugins - GeanyCtags has nothing to do with ProjectOrganizer and knows nothing about ProjectOrganizer's external directories.

I originally created GeanyCtags when tag management in Geany was too slow but now the speed is really good and GeanyCtags is more or less redundant. You should disable it completely and use ProjectOrganizer only. Both Geany's "goto tag definition/declaration" and ProjectOrganizer's "Project->Find project tag" should work for all the tags defined in the project directory and the external directories too.

**Comment by techee** [comment] 2016-01-14 16:22
Uh, "Find project tag" really doesn't seem to work for external directories. Strange, I must have introduced some regression because this (and the symlinks too) used to work. Will have a look at it (probably during the weekend).

**Comment by techee** [comment] 2016-01-14 16:29
OK, I just noticed what you mentioned about the custom language - to be honest I was rather considering removing the GeanyCtags plugin than extending it much since Geany's parsing speed is very good and even for big project it's fast enough. In any case I can have a look if I can fix the symlink problem for GeanyCtags too - then you'd be able to add symlinked directories into the project which should fix your problem.

**Comment by derba** [comment] 2016-01-14 18:32
Thank you for your efforts.

**Comment by techee** [comment] 2016-01-15 16:43
The "Find project tag" should work for external directories too now: https://github.com/geany/geany-plugins/commit/20b545069cf1133c1a33cc333a65d428cd86917d

Please test.

**Comment by derba** [comment] 2016-02-06 16:24
Thank you, it works.

**Closed** 2016-02-06 16:36 UTC
Labels: projectorganizer
