### ISSUE TITLE
geany debugger makes the ide crash (ubuntu 12)

### ISSUE THREAD

**Issue by jmlamare** [geany/geany-plugins#185] opened 2015-01-24 22:26 UTC
Here is the description:
https://bugs.launchpad.net/ubuntu/+source/geany-plugins/+bug/1354747?comments=all

I think the issue is in file "debugger/src/dbm_gdb.c" at line 372 when geany tries to execute gdb command "-exec-run &".
I fix it by removing the character "&"

exec_async_command("-exec-run");

gdb doesn't specify something about this
https://sourceware.org/gdb/current/onlinedocs/gdb/GDB_002fMI-Program-Execution.html#index-g_t_002dexec_002drun-2853

Best regards

**Comment by b4n** [comment] 2015-01-24 22:49
Dupe of #174 and https://sourceforge.net/p/geany-plugins/bugs/112/

**Closed by b4n** 2015-01-24 22:49 UTC
