### ISSUE TITLE
1.27 | C++ | WXUNUSED macro instead of symbol name

### ISSUE THREAD

**Issue by Sawiq** [geany/geany-plugins#799] opened 2018-12-10 14:04 UTC
Geany 1.27 shows WXUNUSED macro in a symbol list instead of a method name while using wxWidgets library. Macro is used to cancel warnings about unused variable.

![obraz](https://user-images.githubusercontent.com/35547519/49737296-c9704800-fc8c-11e8-8266-f783940e2886.png)

**Comment by codebrainz** [comment] 2018-12-10 17:49
I guess that macro is confusing the parser. Not a solution, but why not just leave the argument name out? That's how I avoid unused parameter warnings in C++.

**Comment by b4n** [comment] 2018-12-10 19:34
Dupe of https://github.com/geany/geany/issues/2015

This said, in C++ @codebrainz is right, there's no need to name the argument, and that's kind of the canonical way of avoiding the warning.

**Closed** 2018-12-10 19:52 UTC
