### ISSUE TITLE
Fold all does not work in Split window

### ISSUE THREAD

**Issue by pfortier** [geany/geany-plugins#1220] opened 2023-01-24 13:06 UTC
"Fold all" does not work in "Split window" (n.b. fold all does work in the primary window). 
One has to click each fold manually of the split window.

**Comment by elextr** [comment] 2023-01-25 01:23
Closing as duplicate of #1084 and the others referenced therein.  #1084 explains why.

**Closed by elextr** 2023-01-25 01:23 UTC
