### ISSUE TITLE
[Split Window]: can't save a document in the second window when first and second window don't show the same document

### ISSUE THREAD

**Issue by ralf3u** [geany/geany-plugins#1084] opened 2021-06-18 16:14 UTC
when in the two windows different documents are shown: in the second window I can type words, but I can not save the document (nor with ctrl+s nor with the save-symbol of the tool-bar) 
to save the document: I have to activate the corresponding tab in the first window, and then save is possible

it would be good, when save is possible in the second window, no matter wich document is shown in the first window

possible solution
in Lubuntu 21.04 for example, in the file-manager PCManFM-Qt, there is also the possibility to split the window; but on each window there are tabs; it would be great to have this in Geany; split-window with tabs on each side should be not a plugin but a core element of geany, because it is so cool
at the moment I don't know any editor in the linux world which offers as option a split window with tabs on each side

**Comment by elextr** [comment] 2021-06-19 00:44
Although some editing functions work in it (mostly Scintilla functions that relate to the editing widget), the split window plugin is only intended as a read-only view.  

Unfortunately a lot of Geany functionality relates to the "current document" which is the one in the Geany base editing widget, thats how it was written when nobody had any idea that another window existed since Geany doesn't know anything about what plugins do.  And so a plugin can't be current document as there is no way of providing that information to Geany and the functionality in Geany (like save) can't operate on the second window.

Alternative smart implementations have been tried over time, but performance or other problems have always caused them to fail.

If would be a significant re-write to modify core to handle more than one editing widget, and unless "somebody" is able to provide sufficient effort sadly its unlikely to happen.

Closing as duplicate of #576 #577 #600 #602 #770 #833 and probably others.

Also split window is not in this repository.

**Closed by elextr** 2021-06-19 00:44 UTC

**Comment by rao-pathangi** [comment] 2025-05-08 20:27
Jedit is an editor I can think of that will help with editing in a split screen mode. It requires Java but may not be as polished as Geany or the other options out there.
