### ISSUE TITLE
Vimod in Geany not working

### ISSUE THREAD

**Issue by UlyssesApokin** [geany/geany-plugins#1271] opened 2023-08-21 14:31 UTC
Vimode is not working. When you enable this plugin, I work immediately in insert mode. You cannot switch to normal mode or selections. Esc and ^c don't work. This problem is fixed only by turning off NumLock on the keyboard. But I need it! I don't want to turn NumLock on and off all the time. Obviously this is a bug that needs to be fixed.

Package:
geany-common/jammy,jammy,now 1.38-1 all
geany-plugin-addons/jammy,now 1.38+dfsg-1 amd64

Distro:
Linux Mint 21.2 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
WM:
cinnamon-common/victoria,victoria,now 5.8.4+victoria all

**Comment by elextr** [comment] 2023-08-22 01:56
The numlock is not a defined modifier that [GDK/GTK passes to the application](https://docs.gtk.org/gdk3/flags.ModifierType.html), so Geany may not be able to do anything about it.

It _may_ be mapped to one of the `GDK_MOD[2-5]_MASK` but thats system specific if it does happen, and what it does on a Wayland system is anybodys guess ;-S

**Comment by techee** [comment] 2023-10-05 21:45
This is a duplicate of https://github.com/geany/geany-plugins/issues/1174 and is fixed in master. Closing.

**Closed by techee** 2023-10-05 21:45 UTC
