### ISSUE TITLE
Numberedb bookmarks issue

### ISSUE THREAD

**Issue by Pyxis31** [geany/geany-plugins#1110] opened 2021-09-14 07:28 UTC
mingw-w64-x86_64-geany 1.37.1-3
mingw-w64-x86_64-geany-plugins 1.37.0-2
mingw-w64-x86_64-gtk3 3.24.30-3
Windows 10 pro 21H1

Geany simply doesn't want to start if i install this plugin, if I suppress it all come back right. I reproduced it several time to be sure.

BR

**Comment by elextr** [comment] 2021-09-14 07:37
Likely duplicate of https://github.com/geany/geany-plugins/pull/1106

**Closed** 2021-09-14 07:37 UTC
Labels: duplicate
