### ISSUE TITLE
vimode: line operations cause scrolling and escape doesn't work when numlock enabled

### ISSUE THREAD

**Issue by rishabh-vasudevan** [geany/geany-plugins#1136] opened 2021-11-15 21:15 UTC
I have been using geany with the vimode plugin. Just wanted to share a few places where I found bugs.
1. I am not able to enter normal mode whenever the number lock is on.
2. when I delete a line using the command `dd` the page shifts down till the point the cursor is at the top. Whereas it should have gone the line below and not shifted the page, And when I undo after deleting the line (I have seen this behavior in this particular case only) using `u` the cursor goes to the bottom of the document.

**Comment by techee** [comment] 2021-11-22 23:06
What version of Geany (and the plugin) are you using? Number (1) was indeed a bug in the past version quite a long time ago. I don't remember (2) but it's possible it has been fixed in the meantime too (can't reproduce it here).

**Comment by techee** [comment] 2021-11-23 23:20
OK, I can reproduce (2) now when opening bigger documents and tried to fix it in

https://github.com/geany/geany-plugins/pull/1139

If you are able to compile the code, would you give it a try? This is a regression introduced in 1.38 (in an attempt to fix other problem) so I assume you are using the 1.38 release.

I'll try (1) tomorrow when I have access to an external keyboard with numlock.

**Comment by techee** [comment] 2021-11-24 14:54
Sigh, so yeah, I introduced bug (1) in previous release too. #1141 should fix that.

**Comment by rishabh-vasudevan** [comment] 2021-11-25 05:30
Thank you for now I have downgraded to 1.37 and it works fine, If I get the time I will try to compile this and test it on my system.

**Closed** 2024-05-11 14:35 UTC
Labels: plugin/vimode
