### ISSUE TITLE
debugger plugin not available as debian package

### ISSUE THREAD

**Issue by masla84** [geany/geany-plugins#1020] opened 2020-10-24 08:18 UTC
The debugger plugin is not available as pre-compiled debian image since years.
Maybe related to this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912320
This seems to me a easy-to-solve bug?
Would be great if debugger would return in package index.
Best regards

**Comment by frlan** [comment] 2020-10-24 08:28
Sounds like an packaging issue for me -- isn't it?

**Comment by b4n** [comment] 2020-10-24 08:37
Yep, and even an old report at that: current Debian doesn't have *gdb-python2* anymore.  I guess the reason why the debugger plugin is not in current Debian stable is rather that they have a GTK3 Geany but their version of the plugins don't have a GTK3 support in the debugger plugin.

**Comment by masla84** [comment] 2020-10-24 09:16
I thought "geany-plugins team" is also responsible for debian package. But it's "pkg-geany-team". Sorry.
Anyway, seems like only solution is self-compile? Or is somebody in contact with package maintainers?

**Comment by eht16** [comment] 2020-10-24 09:19
Just wait :).
Geany-Plugins 1.37 will be released tommorrow and then the Debugger plugin can be used with GTK3 again and so the Debian packagers most probably will include it again for the release.

**Comment by masla84** [comment] 2020-10-24 09:19
Great news, thanks!

**Comment by b4n** [comment] 2020-10-24 09:26
> Anyway, seems like only solution is self-compile? Or is somebody in contact with package maintainers?

Yes the only solution is to self-compile for the moment.  Debian won't likely propose a newer version of the plugin in their stable distribution, so nothing on our part will really help.  And the debugger plugin is already available in the testing distribution, which has a new enough version that it supports GTK3.

We could ask @hyperair whether he'd be willing to provide backports, but that's extra work on his shoulders so maybe he'd agree, maybe he wouldn't.

**Comment by masla84** [comment] 2020-10-24 09:42
I use Debian 'Buster' testing, there is no geany-plugin-debugger package available. Also not in unstable distribution.
Search result from https://packages.debian.org:
![grafik](https://user-images.githubusercontent.com/52318651/97078653-d92d7700-15ed-11eb-87cc-e645c9dc3575.png)
Do I miss something?

**Comment by elextr** [comment] 2020-10-24 09:46
Yeah, IIRC correctly debugger didn't get turned back on for 1.36 even though it was GTK3 compatible then, don't know why.

**Comment by b4n** [comment] 2020-10-24 09:54
Hum indeed I don't see it in the repo, yet I though I did earlier… oops.  Anyway, they have a version that would have worked, so I don't know why it hasn't been enabled again, maybe just got forgotten?  @hyperair maybe you could re-enable the debugger plugin in Debian, or tell us if there's something that prevent it that we could fix.

**Comment by codebrainz** [comment] 2020-10-24 19:18
Related to/duplicate of: #756, #758, #942, #957, etc.

**Comment by bxgaillard** [comment] 2023-11-08 13:23
The debugger plugin has been available in Debian since Bullseye (2021), I think this issue can now be closed as resolved.

**Closed** 2024-01-12 09:45 UTC
Labels: plugin/debugger, debian
