### ISSUE TITLE
[WhishList] geany-plugin-markdown

### ISSUE THREAD

**Issue by al-info** [geany/geany-plugins#500] opened 2016-11-10 18:00 UTC
Hi,

I use geany-plugin-markdown to take notes in university. It makes really nice output, but i miss a little feature about image displaying.

I'm using fast relatives names. Using pandoc and latex i make pdf with no problems. But in preview it doesn't work :

![Image preview working](https://tila.im/~al/notnice.png)

I found out how to get a rendering using absolute path :

![Image preview not working](https://tila.im/~al/nice.png)

It's very time costing to type absolute path every time.

Is there an easy way to get relative paths working in WebKit output ?

Thanks for your usefull software :) !

**Comment by codebrainz** [comment] 2016-11-10 21:37
I think relative paths would work if you're in the correct directory. You could test it by changing into the directory to which the images are relative and then running Geany (ex. `$ cd html/foo && geany`). If that works, you could create/update your Geany launcher/shortcut to use the correct working directory.

**Comment by al-info** [comment] 2016-11-11 16:47
Hi,

Thanks for your reply !

I tried your idea, unfortunately it doesn't work. I could have the path searched by the preview engine : right click on broken image link and "copy image adress". Then pasting gave me : file://./image.png

The only way i found to make it work is to give "///absolute/path/to/my/image.png" in the image syntax. The path found is in this case : file:///absolute/path/to/my/image.png

**Comment by codebrainz** [comment] 2016-11-11 18:52
I think the problem lies in [`markdown_viewer_update_view`](https://github.com/geany/geany-plugins/blob/master/markdown/src/viewer.c#L351), it passes the base URI as `file://.`, maybe it should use [`g_get_current_dir()`](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-current-dir) to find the current directory, and compose a proper absolute path for the base URI. The base URI could also be made configurable, but then every time you start editing a different file in another path, it would have to be reconfigured.

**Comment by codebrainz** [comment] 2016-11-11 20:56
Should be fixed in #501, see:

![markdown_relpath](https://cloud.githubusercontent.com/assets/181177/20229971/3454038a-a80e-11e6-924c-1364f3bbfcb5.png)

**Comment by al-info** [comment] 2016-11-11 22:20
Nice !
 
Thank you for the fast fix.

**Comment by codebrainz** [comment] 2016-11-11 23:29
It's not fixed until it's in master :)

**Comment by codebrainz** [comment] 2016-11-11 23:34
Duplicate of #207

**Closed** 2016-11-13 17:23 UTC
Labels: bug, enhancement, plugin/markdown
